"""Transcribes the design's F57 5x7 glyph table into Kotlin.

Two things this has to get right, both silent failures if missed:

  * **Glyph width is per character, not a constant.** The table mixes 1-, 3- and
    5-column glyphs. Padding the narrow ones out to five shifts every character
    that follows them.

  * **Some keys are unicode escapes, not literal characters.** The degree sign is
    written as a six-character escape. A regex that only accepts one character
    between the quotes drops it, and the temperature readout then renders
    "21.5 C" with a hole where the degree mark belongs.
"""
import re
import sys

src, dst = sys.argv[1], sys.argv[2]
html = open(src, encoding="utf-8").read()

KEY = r"'(\\u[0-9A-Fa-f]{4}|\\\\|\\'|[^'])'"
pat = re.compile(KEY + r"\s*:\s*\[\s*(\d+)\s*,\s*\[([^\]]*)\]\s*\]")

rows_out = []
widths = {}
for m in pat.finditer(html):
    ch, w, body = m.group(1), int(m.group(2)), m.group(3)
    vals = [int(v.strip(), 16) for v in body.split(",") if v.strip()]
    if len(vals) != 7:
        continue

    if ch.startswith("\\u"):
        ch = chr(int(ch[2:], 16))
    elif ch == "\\\\":
        ch = "\\"
    elif ch == "\\'":
        ch = "'"

    if ord(ch) > 126:                      # keep the generated Kotlin ASCII-safe
        lit = "\\u%04X" % ord(ch)
    elif ch in ("'", "\\"):
        lit = "\\" + ch
    else:
        lit = ch

    rows_out.append(
        "        '%s' to Glyph(%d, intArrayOf(%s)),"
        % (lit, w, ", ".join("0x%02X" % v for v in vals))
    )
    widths.setdefault(w, []).append(ch)

HEADER = '''package app.tsunagi.e46m3.launcher.ui

/**
 * The LCD's 5x7 glyph table, transcribed verbatim from the design's `F57` map in
 * `E46M3 Launcher v2.dc.html`.
 *
 * Two details are load-bearing:
 *
 *  - **Width is per glyph, not a constant.** The table mixes 1-, 3- and
 *    5-column glyphs (punctuation and the degree sign are narrow). Treating
 *    every glyph as five columns pads them and shifts everything after.
 *  - **Column 0 is bit 0x10.** The design tests `rows[r] & (0x10 >> c)`, so the
 *    leftmost pixel is the high bit of the low five. Reading these as ordinary
 *    LSB-first bytes mirrors every character.
 *
 * Generated by tools/gen_font57.py; do not hand-edit.
 */
object Font57 {
    const val ROWS = 7

    class Glyph(val width: Int, val rows: IntArray)

    val GLYPHS: Map<Char, Glyph> = mapOf(
'''

FOOTER = '''    )

    private val BLANK = Glyph(5, IntArray(ROWS))

    /** Unknown characters fall back to blank, exactly as the design does. */
    fun glyph(c: Char): Glyph = GLYPHS[c.uppercaseChar()] ?: GLYPHS[' '] ?: BLANK
}
'''

open(dst, "w", encoding="utf-8").write(HEADER + "\n".join(rows_out) + "\n" + FOOTER)

print("glyphs:", len(rows_out))
for w in sorted(widths):
    print("  width %d: %s" % (w, " ".join(repr(c) for c in widths[w])))
