"""Converts the design's inline key icons into Android VectorDrawables.

Hand-transcribing nine icons is exactly the kind of task that produces one
silently wrong path, so the SVG is parsed out of the design file instead.

VectorDrawable has no <circle> or <rect> element, only <path>, so those are
converted to path data here. Stroke attributes carry over directly; `fill="none"`
means stroke-only, and `fill="currentColor" stroke="none"` means fill-only.
"""
import re
import sys
import os

# The order icons appear in the design's main screen region.
NAMES = [
    "d_ic_radio", "d_ic_video", "d_ic_eq", "d_ic_map", "d_ic_apps",
    "d_ic_bt", "d_ic_android", "d_ic_carplay", "d_ic_settings",
    "d_ic_tuner", "d_ic_diag", "d_ic_link", "d_ic_settings_m",
    "d_ic_apps_m", "d_ic_home",
    # The app list header's close control. A *different* house glyph from
    # d_ic_home: solid-bottom with a doorway, drawn at 19px, not 20.
    "d_ic_home_solid",
]

SVG = re.compile(r"<svg\b([^>]*)>(.*?)</svg>", re.S)
ATTR = re.compile(r'([a-zA-Z-]+)\s*=\s*"([^"]*)"')


def attrs(s):
    return {k: v for k, v in ATTR.findall(s)}


def circle_path(a):
    cx, cy, r = float(a["cx"]), float(a["cy"]), float(a["r"])
    return (f"M{cx - r:g},{cy:g} a{r:g},{r:g} 0 1,0 {2 * r:g},0 "
            f"a{r:g},{r:g} 0 1,0 {-2 * r:g},0 Z")


def rect_path(a):
    x, y = float(a.get("x", 0)), float(a.get("y", 0))
    w, h = float(a["width"]), float(a["height"])
    r = float(a.get("rx", 0) or 0)
    if r <= 0:
        return f"M{x:g},{y:g} H{x + w:g} V{y + h:g} H{x:g} Z"
    return (f"M{x + r:g},{y:g} H{x + w - r:g} A{r:g},{r:g} 0 0 1 {x + w:g},{y + r:g} "
            f"V{y + h - r:g} A{r:g},{r:g} 0 0 1 {x + w - r:g},{y + h:g} "
            f"H{x + r:g} A{r:g},{r:g} 0 0 1 {x:g},{y + h - r:g} "
            f"V{y + r:g} A{r:g},{r:g} 0 0 1 {x + r:g},{y:g} Z")


CAP = {"round": "round", "square": "square", "butt": "butt"}
JOIN = {"round": "round", "bevel": "bevel", "miter": "miter"}


def emit(svg_attrs, body, out_path):
    root = attrs(svg_attrs)
    vw = root.get("viewBox", "0 0 24 24").split()
    vbw, vbh = vw[2], vw[3]

    parts = []
    for tag, raw in re.findall(r"<(path|circle|rect)\b([^>]*)/?>", body):
        a = attrs(raw)
        if tag == "path":
            d = a.get("d", "")
        elif tag == "circle":
            d = circle_path(a)
        else:
            d = rect_path(a)
        if not d:
            continue

        fill = a.get("fill", root.get("fill", "none"))
        stroke = a.get("stroke", root.get("stroke", "none"))
        sw = a.get("stroke-width", root.get("stroke-width", "1"))
        cap = a.get("stroke-linecap", root.get("stroke-linecap", ""))
        join = a.get("stroke-linejoin", root.get("stroke-linejoin", ""))

        line = ['    <path']
        if fill and fill != "none":
            line.append('        android:fillColor="@color/d_icon"')
        if stroke and stroke != "none":
            line.append('        android:strokeColor="@color/d_icon"')
            line.append(f'        android:strokeWidth="{sw}"')
            if cap in CAP:
                line.append(f'        android:strokeLineCap="{CAP[cap]}"')
            if join in JOIN:
                line.append(f'        android:strokeLineJoin="{JOIN[join]}"')
        line.append(f'        android:pathData="{d.strip()}" />')
        parts.append("\n".join(line))

    xml = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by tools/svg_to_vector.py from the design file. Do not hand-edit. -->\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f'    android:width="{vbw}dp"\n'
        f'    android:height="{vbh}dp"\n'
        f'    android:viewportWidth="{vbw}"\n'
        f'    android:viewportHeight="{vbh}">\n'
        + "\n".join(parts) + "\n</vector>\n"
    )
    open(out_path, "w", encoding="utf-8").write(xml)


def main():
    src, out_dir = sys.argv[1], sys.argv[2]
    html = open(src, encoding="utf-8").read()
    found = SVG.findall(html)
    n = 0
    for i, (sa, body) in enumerate(found):
        if i >= len(NAMES):
            break
        emit(sa, body, os.path.join(out_dir, NAMES[i] + ".xml"))
        n += 1
    print("svgs in file:", len(found), " written:", n)
    for name in NAMES[:n]:
        print("  ", name)


if __name__ == "__main__":
    main()
